version: "3.8"
services:
  mysql:
    container_name: mysql-keycloak
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
       - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: cnam
      MYSQL_DATABASE: keycloak
    networks:
      - better-banking-network  
  keycloak:
    container_name: keycloak2
    image: quay.io/keycloak/keycloak:13.0.1
    ports:
      - "8089:8080"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: cnam
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8089/auth
    depends_on:
      - mysql
    networks:
      - better-banking-network
  redis:
    container_name: better-banking-redis
    image: redis:alpine
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
    restart: on-failure
    networks:
      - better-banking-network
  better-banking:
    container_name: better-banking
    image: better-banking
    ports:
    - 9090:9090
    restart: on-failure
    links:
      - redis
    networks:
      - better-banking-network
    environment:
      - io.betterbanking.integration.url-base=http://localhost:8080
      - keycloak.auth-server-url=http://keycloak:8080/auth

networks:
  better-banking-network:
    external: true

volumes:
  mysql_data:
    driver: local